[project]
name = "linkedin-mcp-server"
version = "1.4.0"
description = "Minimal LinkedIn MCP Server for Docker deployments"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.1",
    "keyring>=25.6.0",
    "keyrings-alt>=5.0.2",  # Provides keyring backend for Docker/Linux
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "patchright>=1.55.0",    # Includes Playwright API - no separate playwright needed!
    "fake-useragent>=1.4.0",
    "asyncio-throttle>=1.0.2",
    "rapidfuzz>=3.13.0",
]

[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"
